In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv ('/content/drive/MyDrive/Advertising_data.csv')

In [5]:
data.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   2210
1   44.5   39.3       45.1   1040
2   17.2   45.9       69.3    930
3  151.5   41.3       58.5   1850
4  180.8   10.8       58.4   1290

In [6]:
data.describe()

TV       radio   newspaper        sales
count  200.000000  200.000000  200.000000   200.000000
mean   147.042500   23.264000   30.554000  1402.250000
std     85.854236   14.846809   21.778621   521.745657
min      0.700000    0.000000    0.300000   160.000000
25%     74.375000    9.975000   12.750000  1037.500000
50%    149.750000   22.900000   25.750000  1290.000000
75%    218.825000   36.525000   45.100000  1740.000000
max    296.400000   49.600000  114.000000  2700.000000

In [7]:
x = data.drop (['sales'], axis =1)
y = data ['sales'].values.reshape(-1,1)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x,y, test_size=0.2, random_state =24)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform (x_train)
x_test = sc.transform (x_test)

In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit (x_train, y_train)

DecisionTreeClassifier()

In [16]:
y_pred = classifier.predict (x_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix (y_test, y_pred)
print (cm)
accuracy_score (y_test, y_pred)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


0.05